apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAdNn6C4arAyMSo/bp4ZP1Uo9jWAyhbAMZL9F7PG7kQFfeoyhLAWLxjrj0cHWcwijsa5AaIN/AYv2diCLv6I1JrYVlTs9ip1tsHDDus55y8+LKTJlfzsyr6Nb1A95J6GZ9rMsqC3oSicMk093LV9foIIGRk3UTKS5DoZG8aPNdeNXxSDz9CBQ63DRKzSs8T4aAjXmtUg+Hhfi0nZbXdZcilWG3/RkpKPBdLXjxhRTUqR+lBqNrHS8rgwhTl8MFI4NIhQNnhE78d4OL2F/DHkt0IrUu3FE7MqHgktsyJ0x6f2pJC2H0BltR3ZQrDqMx/Kdtx1msWwJLRCIHVsz029aEnZXhUNRmHTGCMCKALT+goDMMb4EoHD1VughH8CFq1GvcSsveHC54kO1o+0BoTdqwpzRHJxlRQgyRoXsYO754XTd0Zw7Z5QQJXZAzp/HA/u2FtKK4eKlTzkUUfz5wWYheGE27kFMBJUBlDQASvDeHAN+Z2UQuDgMOw0ftx4fYYz7c09V3EHyolY2NI9+Xh9OGSwoy2QN79pWBj1eBfrPadfdg9EtPDfE7v8OYZKtbcm5h0m6zsdkWCAQ5MDD4v92fdkcW4Kk8fm+w1UK/XcWqV7iqUJ4MsQWcvhqab8o0cOISvxa6P8U9KLKXv7TaI69RCzE4L9EJ6CNmRLvIPLAMnFZa7ZsgfhCDMQ/sA9JMZqrp9DVulsNc77tVvXNxsD/drdaZD9d+pLtFHxGcaFLtmrgjQabEd1iba54Sjooo8q8p34VQmFM/Ljyg9ezJn2vWzLH+5fpn8rseftQsl+Qmgq3OXMMtUibNq48Zflug1xWWB1hYumonP4+mFhcqiAHstx3497BTd4DgK6Hwx7+iss/E83o/h002s9dJ2yQ54d7fBq52JLlfw1L5zfAgkNtx27sq/0PZOTEbnGpZgPfu6hTscNQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: dockerhub
      namespace: default
    type: kubernetes.io/dockerconfigjson